typography_spectrum: 0.989276397973299
color:
  brandStrength: 0.706115314969793
  lightness: 0.26352508645504713
  saturation: 0.4470093681011349
  rhythmicContrast: 0.594755575992167
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
opengraph:
  type: omahaholidayhouses
layout_spectrum: 0.4094260309357196
author:
  name: Concierge
  email: manager@omahaholidayhouses.co.nz
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/54df1f0f-ed98-43de-90ca-c10e283751cb.jpg
name: Northern Escape
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/47ab832b-fc9d-484f-b8c3-e665f2fda643.ico
title: Northern Escapes
description: World Class adventures north of Auckland
