typography_spectrum: 0.49616400455124676
color:
  brandStrength: 0.6737363925203681
  lightness: 0.33178488072007895
  saturation: 0.031829398358240724
  rhythmicContrast: 0.7080695577897131
  brandColors:
    - '#19171B'
    - '#009DE0'
    - '#FCC300'
    - '#B07D3F'
    - '#0000FF'
opengraph:
  type: omahaholidayhouses
layout_spectrum: 0.010733271483331919
author:
  name: Concierge
  email: manager@omahaholidayhouses.co.nz
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/54df1f0f-ed98-43de-90ca-c10e283751cb.jpg
name: Northern Escape
navigation:
  - name: The best accommodation experience north of Auckland
    url: 'http://www.omahaholidayhouses.co.nz'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/47ab832b-fc9d-484f-b8c3-e665f2fda643.ico
title: Stay Matakana
description: World Class adventures north of Auckland
